#!/usr/bin/env bash
set -xe

###############################################################################
#  Celestial Navigation Plugin — Cloudsmith Upload Script (MSVC / Windows)
#
#  Purpose:
#    • Post‑process MSVC build artifacts produced by CMake/CPack
#    • Insert correct metadata.xml into the packaged tarball
#    • Construct correct Cloudsmith package naming conventions
#    • Upload tarball + installer package to the correct Cloudsmith repos
#
#  Features:
#    • Windows‑safe tarball repack (gunzip/tar/gzip)
#    • Uses PROJECT_VERSION, PKG_TARGET, PKG_TARGET_VERSION from pkg_version.sh
#    • Automatically determines ALPHA/BETA/PROD repo based on branch/tag
#    • Supports CircleCI, AppVeyor, Travis, and local MSVC builds
#    • Skips upload for LOCAL builds (no API key required)
#
#  Cloudsmith Repositories (actual names):
#       opencpn/celestial-navigation-alpha
#       opencpn/celestial-navigation-beta
#       opencpn/celestial-navigation-prod
#
#  Expected Build Artifacts (in build/):
#       celestial_navigation_pi-*.xml
#       celestial_navigation_pi-*.tar.gz
#       celestial_navigation_pi-*.exe  (MSVC installer)
#
#  Usage:
#       From plugin root:
#           bash ./cloudsmith-upload2.sh
#
#       From build directory:
#           bash ../cloudsmith-upload2.sh
#
#  Notes:
#       • This script must reside in the plugin root directory.
#       • pkg_version.sh must exist in build/ and be generated by CMake.
#       • This script replaces older Climatology-style upload scripts.
#
###############################################################################

############################################
# Resolve plugin root and build directory
############################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$SCRIPT_DIR"
BUILD_DIR="$PLUGIN_ROOT/build"

echo "SCRIPT_DIR:  $SCRIPT_DIR"
echo "PLUGIN_ROOT: $PLUGIN_ROOT"
echo "BUILD_DIR:   $BUILD_DIR"

############################################
# Cloudsmith repo definitions (actual names)
############################################

PROD_REPO=${CLOUDSMITH_PROD_REPO:-'opencpn/celestial-navigation-prod'}
BETA_REPO=${CLOUDSMITH_BETA_REPO:-'opencpn/celestial-navigation-beta'}
ALPHA_REPO=${CLOUDSMITH_ALPHA_REPO:-'opencpn/celestial-navigation-alpha'}

############################################
# Determine build environment
############################################

LOCAL_BUILD=false

if [ "$CIRCLECI" ]; then
    BUILD_ID=${CIRCLE_BUILD_NUM:-1}
    BUILD_BRANCH=$CIRCLE_BRANCH
    BUILD_TAG=$CIRCLE_TAG
    PKG_EXT=${CLOUDSMITH_PKG_EXT:-'deb'}

elif [ "$APPVEYOR" ]; then
    BUILD_ID=${APPVEYOR_BUILD_NUMBER:-1}
    BUILD_BRANCH=$APPVEYOR_REPO_BRANCH
    BUILD_TAG=$APPVEYOR_REPO_TAG_NAME
    PKG_EXT=${CLOUDSMITH_PKG_EXT:-'exe'}

else
    BUILD_ID=1
    BUILD_BRANCH=""
    BUILD_TAG=""
    PKG_EXT=${CLOUDSMITH_PKG_EXT:-'exe'}
    LOCAL_BUILD=true
fi

############################################
# API key check (skip for local builds)
############################################

set +x
if [ -z "$CLOUDSMITH_API_KEY" ] && [ "$LOCAL_BUILD" = "false" ]; then
    echo "Missing CLOUDSMITH_API_KEY — skipping upload"
    exit 0
fi
set -x

############################################
# Git info
############################################

commit=$(git -C "$PLUGIN_ROOT" rev-parse --short=7 HEAD || echo "unknown")

############################################
# Load version info from CMake
############################################

source "$BUILD_DIR/pkg_version.sh"

PACKAGE_NAME="celestial_navigation_pi"
ARCH="x86"

############################################
# Determine repo and VERSION
############################################

BUILD_BRANCH_LOWER=$(echo "$BUILD_BRANCH" | tr 'A-Z' 'a-z')

if [ "$BUILD_BRANCH_LOWER" = "master" ]; then
    if [ -n "$BUILD_TAG" ]; then
        VERSION="$BUILD_TAG"
        REPO="$PROD_REPO"
    else
        VERSION="${PROJECT_VERSION}+${BUILD_ID}.${commit}"
        REPO="$BETA_REPO"
    fi
else
    if [ -n "$BUILD_TAG" ]; then
        VERSION="$BUILD_TAG"
        REPO="$BETA_REPO"
    else
        VERSION="${PROJECT_VERSION}+${BUILD_ID}.${commit}"
        REPO="$ALPHA_REPO"
    fi
fi

echo "VERSION: $VERSION"
echo "REPO:    $REPO"

############################################
# Build correct tarball name
############################################

tarball_name="${PACKAGE_NAME}-${VERSION}-msvc-${ARCH}-wx32-${PKG_TARGET_VERSION}-MSVC"

echo "TARBALL NAME: $tarball_name"

############################################
# Locate artifacts
############################################

cd "$BUILD_DIR"

xml=$(ls ${PACKAGE_NAME}-*.xml 2>/dev/null || echo "")
tarball=$(ls *.tar.gz 2>/dev/null || echo "")
pkg=$(ls *.${PKG_EXT} 2>/dev/null || echo "")

if [ -z "$xml" ]; then
    echo "ERROR: No XML file found (expected ${PACKAGE_NAME}-*.xml)"
    exit 1
fi

if [ -z "$tarball" ]; then
    echo "ERROR: No tar.gz file found"
    exit 1
fi

tarball_basename=${tarball##*/}

############################################
# Windows-safe XML substitution
############################################

while read -r line; do
    line=${line//--pkg_repo--/$REPO}
    line=${line//--name--/$tarball_name}
    line=${line//--version--/$VERSION}
    line=${line//--filename--/$tarball_basename}
    echo "$line"
done < "$xml" > xml.tmp

mv xml.tmp "$xml"

############################################
# Repack tarball with metadata.xml
############################################

gunzip -f "$tarball"
tarball_tar="${tarball%.gz}"

cp "$xml" metadata.xml
tar -rf "$tarball_tar" metadata.xml
gzip -f "$tarball_tar"

############################################
# Upload (skip for local builds)
############################################

if [ "$LOCAL_BUILD" = true ]; then
    echo "Local Windows build — skipping Cloudsmith upload"
    exit 0
fi

cloudsmith push raw --republish --no-wait-for-sync \
    --name "${tarball_name}" \
    --version "${VERSION}" \
    --summary "Celestial Navigation plugin tarball" \
    "$REPO" "$tarball"

if [ -n "$pkg" ]; then
    cloudsmith push raw --republish --no-wait-for-sync \
        --name "celestial-navigation-package-${VERSION}.${PKG_EXT}" \
        --version "${VERSION}" \
        --summary "Celestial Navigation installer package" \
        "$REPO" "$pkg"
fi

echo "Cloudsmith upload complete."
