#!/usr/bin/env python3
"""Explicit maintainer-only IERS acquisition; never run during build/startup."""
import argparse
import datetime as dt
import hashlib
import json
import math
from pathlib import Path
import urllib.request

SOURCES = {
    "C04": "https://datacenter.iers.org/data/latestVersion/EOP_20u24_C04_one_file_1962-now.txt",
    "finals": "https://datacenter.iers.org/data/9/finals2000A.all",
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive",type=Path,required=True)
    args = parser.parse_args()
    args.archive.mkdir(parents=True,exist_ok=False)
    root = Path(__file__).resolve().parents[1]
    records, provenance = {}, {}
    for name,url in SOURCES.items():
        with urllib.request.urlopen(url,timeout=60) as response:
            raw = response.read()
        (args.archive/(name+".txt")).write_bytes(raw)
        provenance[name] = {"url":url,"sha256":hashlib.sha256(raw).hexdigest(),
                            "retrieved_utc":dt.datetime.now(dt.timezone.utc).isoformat()}
        count = 0
        for line in raw.decode("ascii").splitlines():
            if name == "C04":
                if not line.strip() or line.lstrip().startswith("#"): continue
                fields = line.split()
                if len(fields) != 21: raise ValueError("Unexpected C04 column count")
                year,month,day,hour = map(int,fields[:4])
                if hour != 0: raise ValueError("C04 must be midnight UTC")
                mjd,value,quality = float(fields[4]),float(fields[7]),"C"
            else:
                if not line[58:68].strip(): continue
                mjd,value,quality = float(line[7:15]),float(line[58:68]),line[57]
                year,month,day = int(line[:2]),int(line[2:4]),int(line[4:6])
                year += 1900 if mjd < 51544 else 2000
                if quality not in ("I","P"): raise ValueError("Unexpected finals quality")
            date = dt.date(year,month,day)
            if mjd != (date-dt.date(1858,11,17)).days:
                raise ValueError("Source MJD/date mismatch")
            if date < dt.date(1972,1,1): continue
            if not math.isfinite(value) or abs(value)>0.95:
                raise ValueError("Invalid DUT1")
            # Prefer the final C04 history; append rapid values/predictions.
            records.setdefault(int(mjd),(value,quality))
            count += 1
        provenance[name]["accepted_rows"] = count
    days = sorted(records)
    if len(days)<19000 or any(b-a!=1 for a,b in zip(days,days[1:])):
        raise ValueError("Incomplete or discontinuous IERS daily coverage")
    output = "// Generated by tools/update_dut1.py; see data/earth-orientation-provenance.json.\n"
    output += "// MJD at 0h UTC, UT1-UTC seconds, C=final C04 / I=rapid / P=predicted.\n"
    output += "".join(f"  {{{d}, {records[d][0]:.7f}, '{records[d][1]}' }},\n" for d in days)
    target = root/"eclipse/src/dut1_data.inc"
    target.write_text(output)
    provenance.update({"generated_utc":dt.datetime.now(dt.timezone.utc).isoformat(),
        "data_sha256":hashlib.sha256(output.encode()).hexdigest(),"count":len(days),
        "start_utc":str(dt.date(1858,11,17)+dt.timedelta(days=days[0])),
        "end_utc":str(dt.date(1858,11,17)+dt.timedelta(days=days[-1])),
        "policy":"Final C04 history then Bulletin A rapid/predicted UT1-UTC; no extrapolation"})
    (root/"data/earth-orientation-provenance.json").write_text(json.dumps(provenance,indent=2)+"\n")
    print(json.dumps(provenance,indent=2))


if __name__ == "__main__": main()
